### ISSUE TITLE
f:$(color-variable) seems not working

### ISSUE THREAD

**Issue by EasonLin0716** [master-co/styles#8]
Hi,
I hope you're doing well.

I've faced an issue, if I put a variable in :root and use it in class:
```html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Some</title>
    <link href="https://unpkg.com/@master/normal.css" rel="stylesheet" />
    <script src="https://unpkg.com/@master/style"></script>
    <script src="https://unpkg.com/@master/styles"></script>

    <style>
      html,
      body {
        height: 100%;
      }
      :root {
        --light-grey: hsl(217, 12%, 63%);
      }
    </style>
  </head>
  <body>
    <p class="font-color:$(light-grey)">Hey man!</p>
  </body>
</html>

```

This would work perfect. However if I change p tag to:
```html
<p class="f:$(light-grey)">Hey man!</p>
```
it will not work as expected.
Official doc here: https://docs.master.co/styles/font-color
says I can use f as a shorthand of font-color, Not sure if `f:$(light-grey)` is illegal or this is a bug.

**Comment by BenSeage** [comment]
f:**_color_** can only be used with the official color variables, e.g. **f:red**, **f:blue-50**, **f:red-60**...

You must be confused why css variables can't be used, 
because the css variables could be color/style/size or something else,
we unable to determine whether **f:$(light-grey)** is belongs to [font-color](https://docs.master.co/styles/font-color) property.

In conclusion, if you want to use font-color with variables, you must type **font-color:$(...)**.
